services:
  # ClickHouse database
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - 8143:8123
      - 9004:9000
    volumes:
      - /data/docker/hass/clickhouse:/var/lib/clickhouse
    env_file: .env
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144