services:
  # Dagster webserver
  dagster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3033:3000"
    volumes:
      - ./hass_datasette_etl:/app/hass_datasette_etl
      - dagster_home:/app/dagster_home
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # ClickHouse database
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8143:8123"  # HTTP interface
      - "9004:9000"  # Native interface
    volumes:
      - /data/docker/hass/clickhouse:/var/lib/clickhouse
    env_file: .env
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  dagster_home:
