services:
  # Dagster webserver
  dagster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3033:3000"
    volumes:
      - ./hass_datasette_etl:/app/hass_datasette_etl
      - dagster_home:/app/dagster_home
    env_file:
      - .env
    environment:
      - DAGSTER_BASE_URL=http://localhost:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  dagster_home: