
version: 2

sources:
  - name: raw
    database: raw
    tables:
      - name: statistics
      - name: statistics_meta
      - name: events
      - name: event_data
      - name: event_types

models:
  - name: stg_statistics
    description: "Home Assistant 5min aggregate statistics"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - not_null
  - name: stg_statistics_meta
    description: "Home Assistant statistics metadata"
  - name: stg_events
    description: "Individual events"
  - name: stg_event_data
    description: "JSON event data"
  - name: stg_event_types
    description: "Event categories"
