
version: 2

models:
  - name: statistics
    description: "Home Assistant 5min aggregate statistics"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
  - name: events
    description: "Home Assistant granular events"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - non_null